### ISSUE TITLE
[BUG] Full-screen windows are not counted in recently used order for window switcher

### ISSUE THREAD

**Issue by 64-bitman** [G-dH/advanced-alttab-window-switcher#126] opened 2024-10-21 03:33 UTC
**Describe the bug**

**To Reproduce**
1. Open a fullscreen window
2. Open two other windows
3. Open fullscreen window
4. Alt-tab
5. Alt-tab again
6. Window is not the fullscreen one

**Expected behavior**
Fullscreen window should be put as recently used

**Desktop (please complete the following information):**
 - OS: Fedora 41
 - Version of the extension: v46.2-28-g4bab39a
 - Git repo

**Comment by G-dH** [comment] 2024-10-21 06:12
Can you reproduce this bug with AATWS disabled?

**Comment by 64-bitman** [comment] 2024-10-21 14:31
I can reproduce this when the extension is disabled.

**Comment by G-dH** [comment] 2024-10-21 14:57
In this case the issue is related to another extension or GNOME Shell itself. I'm unable to reproduce this issue on my Fedora 41.

**Comment by G-dH** [comment] 2024-10-27 06:35
Closing as invalid. Feel free to reopen the issue if you disagree.

**Closed** 2024-10-27 06:35 UTC
Labels: invalid
