### ISSUE TITLE
[BUG] can't add delete / escape as keyboard shortcut

### ISSUE THREAD

**Issue by pacjo** [G-dH/advanced-alttab-window-switcher#78] opened 2023-11-09 13:49 UTC
**Describe the bug**
I wanted to have an ability to close selected window by pressing delete (just like windows does it). It currently isn't possible.

**To Reproduce**
1. Go to extension settings -> `Hotkeys`
2. Click on `Close window / Quit application`
4. Can't add delete / escape key (possibly others too)

**Expected behavior**
An option to select / add delete / escape

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Version of the extension: 26
 - Source of installation: [Extension manager](https://github.com/mjakeman/extension-manager)

**Comment by G-dH** [comment] 2023-11-24 16:47
No special keys can be assigned as hotkeys in AATWS, it's a feature, not a bug. Delete key is for deleting searched pattern and Esc key closes the switcher popup. The Del key for closing windows could be added as an option if the search feature is disabled..

**Comment by pacjo** [comment] 2023-11-24 19:55
> The Del key for closing windows could be added as an option if the search feature is disabled.

Sounds good. Is it possible right now does it need to be implemented?

**Comment by G-dH** [comment] 2023-12-05 22:02
Sorry, I forgot to answer.. It is not possible at the moment, it's on my to-do list.

**Closed** 2024-10-21 06:56 UTC
Labels: feature, fixed
